---
site_name: "monarch-data"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: practice.md
site_url: https://monarchinitiative.github.io/monarch-data
repo_url: https://github.com/monarchinitiative/monarch-data

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
