---
name: Auto-deployment of data_sheets_schema Documentation
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN permissions to make a Pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # to verify deployment is from appropriate source

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry.
        uses: snok/install-poetry@v1.3

      - name: Install dependencies.
        run: poetry install -E docs

      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          make mkd-gh-deploy
